ch_num: 1

cameras:
  - id: 0
    url: "http://59.14.95.196:1188/cam"
    width: 320
    height: 240
    type: "thermal"
  - id: 1
    url: "http://admin:dongbuict0@59.14.95.196:6480/ISAPI/Streaming/channels/202/httpPreview"
    width: 320
    height: 240
    type: "thermal"

detectors:
  - id: 0
    enable: True
    model: "yolov8s_apink_100ep.pt"
    conf: 0.5
    iou: 0.5
    event:
      type: "reverse"
      roi:
      single:
        - [0.8, 0.5]
        - [0.5, 0.8]
      start:
      end:
  - id: 1
    enable: False
    model: "yolov8s_apink_100ep.pt"
    conf: 0.5
    iou: 0.5
    event:
      type: "reverse"
      roi:
      single:
      start:
      end:

hardware:
  uart:
    driver: '/dev/ttyTHS0'
    baudrate: 115200