channel_num: 2

cameras:
  - id: 0
    url: "http://59.14.95.196:1188/cam"
    width: 320
    height: 240
    type: "thermal"
  - id: 1
    url: "http://59.14.95.196:1188/cam"
    width: 320
    height: 240
    type: "thermal"

detectors:
  - id: 0
    model: "yolov8n_apink"
    conf: 0.5
    iou: 0.5
    rois:
      - id: 0
        pts:
          - [0.3, 0.3]
          - [0.7, 0.3]
          - [0.7, 0.7]
          - [0.3, 0.7]
        event: "left" 
    lines:
      - id: 0
        event: "reverse"
        type: "start"
        pts:
          - [0.4, 0,1]
          - [0.1, 0.4]
      - id: 1
        event: "reverse"
        type: "end"
        pts:
          - [0.8, 0.5]
          - [0.5, 0.8]
  - id: 1
    model:
    conf:
    iou:
    rois:
    lines:

models:
  - yolov8n_apink_10ep.pt
  - yolov8s_apink_100ep.pt